Repository NOAA-EMC/WW3, pull requests merged in 2021-09, with the labels that each got.

#444 UKMO SMC Bugfixes [Staging Aug 2021]
  model/ftn/w3ounfmetamd.ftn
  model/ftn/w3smcomd.ftn
  model/ftn/ww3_ounf.ftn
  regtests/ww3_tp2.16/input/ww3_ounf.inp
Labels: bug

#473 Add ESMF profile memory statements
  model/ftn/wmesmfmd.ftn
Labels: new feature

#482 Manual PDF build errors
  manual/manual.bib
  manual/num/space_SMC.tex
  manual/run.tex
  manual/sys.tex
  model/inp/ww3_shel.inp
Labels: bug, documentation

#468 Add support for regression tests on NCEP RDHPC orion machine
  model/bin/cmplr.env
  regtests/bin/matrix.base
  regtests/bin/matrix_ncep
Labels: enhancement

#481 bug fix for Portland compiler
  model/ftn/w3iorsmd.ftn
Labels: bug
