Repository NOAA-EMC/WW3, pull requests merged in 2022-04, with the labels that each got.

#648 Merge develop to dev/ufs-weather-model branch 20220324
  CMakeLists.txt
  manual/eqs/output.tex
  model/inp/ww3_shel.inp
  model/nml/ww3_multi.nml
  model/nml/ww3_shel.nml
  model/tools/bash/ww3_multi_inp2nml.sh
  model/tools/bash/ww3_ounf_inp2nml.sh
  model/tools/bash/ww3_shel_inp2nml.sh
  regtests/bin/matrix_cmake_ncep
  regtests/bin/run_cmake_test
Labels: UFS

#637 Scal local
  model/src/PDLIB/yowelementpool.F90
  model/src/PDLIB/yowexchangeModule.F90
  model/src/PDLIB/yownodepool.F90
  model/src/PDLIB/yowpdlibmain.F90
  model/src/constants.F90
  model/src/w3adatmd.F90
  model/src/w3dispmd.F90
  model/src/w3gdatmd.F90
  model/src/w3gridmd.F90
  model/src/w3initmd.F90
  model/src/w3iorsmd.F90
  model/src/w3meminfo.F90
  model/src/w3parall.F90
  model/src/w3profsmd.F90
  model/src/w3profsmd_pdlib.F90
  model/src/w3ref1md.F90
  model/src/w3srcemd.F90
  model/src/w3triamd.F90
  model/src/w3updtmd.F90
  model/src/w3wavemd.F90
  model/src/w3wdatmd.F90
  model/src/wmesmfmd.F90
  model/src/wmgridmd.F90
  model/src/wminitmd.F90
  model/src/wmscrpmd.F90
  model/src/ww3_ounf.F90
  model/src/ww3_prep.F90
  model/src/ww3_prnc.F90
  model/src/ww3_prtide.F90
  model/src/ww3_shel.F90
  regtests/ww3_tp2.17/input/ww3_shel.inp
  regtests/ww3_tp2.6/input/ww3_shel.inp
  regtests/ww3_tp2.6/input/ww3_shel.nml
Labels: enhancement

#658 Bugfix/cmake netcdf find
  CMakeLists.txt
  model/README.md
  model/src/CMakeLists.txt
  regtests/bin/matrix_cmake_ukmo_cray
  regtests/bin/run_cmake_test
  regtests/ww3_tp2.14/input/oasis3-mct/util/make_dir/CMakeLists.txt
  regtests/ww3_tp2.14/input/oasis3-mct/util/make_dir/cmplr.tmpl
  regtests/ww3_tp2.14/input_oasacm/prep_env.sh
  regtests/ww3_tp2.14/input_oasacm2/prep_env.sh
  regtests/ww3_tp2.14/input_oasacm4/prep_env.sh
  regtests/ww3_tp2.14/input_oasacm5/prep_env.sh
  regtests/ww3_tp2.14/input_oasacm6/prep_env.sh
  regtests/ww3_tp2.14/input_oasicm/prep_env.sh
  regtests/ww3_tp2.14/input_oasocm/prep_env.sh
Labels: bug, enhancement
